In [1]:
import torch

In [2]:
print(torch.__version__)

2.7.0+cu118


In [3]:
torch.ones(5)

tensor([1., 1., 1., 1., 1.])

In [4]:
import numpy as np

In [5]:
n = np.ones(5)

t = torch.from_numpy(n)

In [7]:
# Directly from data

data = [[1, 2],[3, 4]]

x_data = torch.tensor(data)

print(x_data)

tensor([[1, 2],
        [3, 4]])


In [8]:
# Above execution is very similar to np.array(data)
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [9]:
# If you want to get/fetch the data or values from Numpy's arrays to Torch's tensors. use the function called `from_numpy(n)`

In [10]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [11]:
print("numpy values:",n)

numpy values: [1. 1. 1. 1. 1.]


In [12]:
print("torch values:",t)

torch values: tensor([1., 1., 1., 1., 1.], dtype=torch.float64)


In [13]:
# Changes in the NumPy array reflects in the tensor.    

In [14]:
np.add(n, 1, out=n)       # adding 1 into each element of numpy array n
print(f"torch: {t}")
print(f"numpy: {n}")

torch: tensor([2., 2., 2., 2., 2.], dtype=torch.float64)
numpy: [2. 2. 2. 2. 2.]


In [15]:
# From another tensor:
print(f"original x_data: \n {x_data} \n")

x_ones = torch.ones_like(x_data)           # retains the properties (shape, datatype) of x_data
print(f"Ones Tensor: \n {x_ones} \n")

original x_data: 
 tensor([[1, 2],
        [3, 4]]) 

Ones Tensor: 
 tensor([[1, 1],
        [1, 1]]) 



In [16]:
x_rand = torch.rand_like(x_data, dtype=torch.float)       # overrides the datatype of x_data
print(f"Random Tensor: \n {x_rand} \n")

Random Tensor: 
 tensor([[0.9826, 0.1455],
        [0.4278, 0.1280]]) 



In [17]:
rng=np.random.default_rng()                              # this is how random generation works in numpy
rng.random((2,3))

array([[0.17822418, 0.46860646, 0.75271628],
       [0.46103233, 0.48006807, 0.43083757]])

In [18]:
# WITH RANDOM OR CONSTANT VALUES

shape = (2, 3,)
rand_tensor = torch.rand(shape)                   # Random values of tensors would be generated
ones_tensor = torch.ones(shape)
zeros_tensor = torch.zeros(shape)

print(f"Random Tensor: \n {rand_tensor} \n")
print(f"Ones Tensor: \n {ones_tensor} \n")
print(f"Zeros Tensor: \n {zeros_tensor}")

Random Tensor: 
 tensor([[0.9296, 0.5717, 0.9880],
        [0.0903, 0.3451, 0.1241]]) 

Ones Tensor: 
 tensor([[1., 1., 1.],
        [1., 1., 1.]]) 

Zeros Tensor: 
 tensor([[0., 0., 0.],
        [0., 0., 0.]])


In [19]:
# ATTRIBUTES OF TENSORS

tensor = torch.rand(3,4)

print(f"Shape of tensor: {tensor.shape}")
print(f"Datatype of tensor: {tensor.dtype}")
print(f"Device tensor is stored on: {tensor.device}")

Shape of tensor: torch.Size([3, 4])
Datatype of tensor: torch.float32
Device tensor is stored on: cpu


In [21]:
# Joining tensors You can use torch.cat to concatenate a sequence of tensors along a given dimension.

t1 = torch.cat([tensor, tensor, tensor], dim=1)
print(t1)
print(t1.shape)

tensor([[0.6594, 0.4951, 0.2227, 0.3559, 0.6594, 0.4951, 0.2227, 0.3559, 0.6594,
         0.4951, 0.2227, 0.3559],
        [0.4892, 0.8530, 0.4342, 0.4227, 0.4892, 0.8530, 0.4342, 0.4227, 0.4892,
         0.8530, 0.4342, 0.4227],
        [0.7137, 0.6214, 0.4395, 0.5251, 0.7137, 0.6214, 0.4395, 0.5251, 0.7137,
         0.6214, 0.4395, 0.5251]])
torch.Size([3, 12])
