In [4]:
# create model class
import torch
import torch.nn as nn

class Model(nn.Module):
  """This is very basix example of creating model class"""
  def __init__(self, num_features):

    super().__init__()                              # calling __init__() method of parent class nn.Module
    self.linear = nn.Linear(num_features, 1)        # z = wx + b (used linear layer)
    self.sigmoid = nn.Sigmoid()                     # sigmoid activation function

  def forward(self, features):

    out = self.linear(features)       # here getting z = wx + b
    out = self.sigmoid(out)           # here getting sigmoid(z) .... dz/dy

    return out

In [35]:
# create model class
import torch
import torch.nn as nn

class Model(nn.Module):

  def __init__(self, num_features):

    super().__init__()
    """
    THIS RED CODES ARE WORKING TOGETHER IN FORWARD METHOD AND MODEL CLASS. SO UNCOMMENT BOTH TOGETHER

    self.linear1 = nn.Linear(num_features, 3)
    self.relu = nn.ReLU()
    self.linear2 = nn.Linear(3, 1)
    self.sigmoid = nn.Sigmoid()
    """
    # Let's sy if we have more than 1000 inputs(features) and we need to create neural networks. In this case, we have container concept.
    # we will use "Sequential" containers to make it customized and short

    self.network = nn.Sequential(
        nn.Linear(num_features, 3),
        nn.ReLU(),
        nn.Linear(3, 1),
        nn.Sigmoid()
    )


  def forward(self, features):
    """
    out = self.linear1(features)
    out = self.relu(out)
    out = self.linear2(out)
    out = self.sigmoid(out)
    """
    # If using Sequential container, just pass features into self.network variable.
    out = self.network(features)


    return out

In [36]:
# create dataset
features = torch.rand(10,5)         # 5 columns taken because we took 5 features in neural network

features

tensor([[0.6864, 0.0561, 0.8502, 0.3982, 0.1301],
        [0.2758, 0.0201, 0.8112, 0.3043, 0.5951],
        [0.3390, 0.2909, 0.7307, 0.6637, 0.9971],
        [0.3710, 0.0090, 0.4525, 0.7655, 0.3741],
        [0.7045, 0.5379, 0.0168, 0.9585, 0.5074],
        [0.0200, 0.6226, 0.1428, 0.8268, 0.9185],
        [0.3824, 0.7041, 0.3280, 0.9696, 0.4036],
        [0.3027, 0.9436, 0.1018, 0.2155, 0.1719],
        [0.3859, 0.9727, 0.5457, 0.7627, 0.7706],
        [0.0359, 0.7556, 0.4467, 0.0979, 0.4725]])

In [37]:
# create model
model = Model(features.shape[1])

In [38]:
# call model for forward pass
# model.forward(features)       # we called this way in Python but it is advisable to use as below. just call the function by attributes
model(features)

tensor([[0.5697],
        [0.5697],
        [0.5697],
        [0.5697],
        [0.5697],
        [0.5697],
        [0.5697],
        [0.5697],
        [0.5697],
        [0.5697]], grad_fn=<SigmoidBackward0>)

In [ ]:
# show model weights
# model.linear2.weight

In [45]:
# show model weights
print("Weights of the first linear layer:")
print(model.network[0].weight)

Weights of the first linear layer:
Parameter containing:
tensor([[-0.2695, -0.0655, -0.2061, -0.1292, -0.3170],
        [-0.0371,  0.1083, -0.1677, -0.3630,  0.0528],
        [ 0.0802, -0.1280, -0.2648, -0.2853,  0.2890]], requires_grad=True)


In [46]:
print("\nWeights of the second linear layer:")
print(model.network[2].weight)


Weights of the second linear layer:
Parameter containing:
tensor([[ 0.3439,  0.4906, -0.2688]], requires_grad=True)


In [33]:
!pip install torchinfo

In [47]:
# torchinfo library is used to visualize the data output

from torchinfo import summary

summary(model, input_size=(10, 5))

Layer (type:depth-idx)                   Output Shape              Param #
Model                                    [10, 1]                   --
├─Sequential: 1-1                        [10, 1]                   --
│    └─Linear: 2-1                       [10, 3]                   18
│    └─ReLU: 2-2                         [10, 3]                   --
│    └─Linear: 2-3                       [10, 1]                   4
│    └─Sigmoid: 2-4                      [10, 1]                   --
Total params: 22
Trainable params: 22
Non-trainable params: 0
Total mult-adds (Units.MEGABYTES): 0.00
Input size (MB): 0.00
Forward/backward pass size (MB): 0.00
Params size (MB): 0.00
Estimated Total Size (MB): 0.00