In [2]:
import torch
print(torch.__version__)

2.7.0+cu118


In [2]:
if torch.cuda.is_available():
    print("GPU is available!")
    print(f"Using GPU: {torch.cuda.get_device_name(0)}")
else:
    print("GPU not available. Using CPU.")

GPU is available!
Using GPU: Tesla T4


## Creating a Tensor

In [3]:
# using empty
a = torch.empty(2,3)

In [4]:
# check type
type(a)

torch.Tensor

In [5]:
# using zeros
torch.zeros(2,3)

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [6]:
# using ones
torch.ones(2,3)

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [7]:
# using rand
torch.rand(2,3)

tensor([[0.2392, 0.5974, 0.6683],
        [0.3516, 0.6863, 0.9163]])

In [8]:
# use of seed
torch.rand(2,3)

tensor([[0.2940, 0.9409, 0.3265],
        [0.0266, 0.2275, 0.9552]])

In [9]:
# manual_seed
torch.manual_seed(100)
torch.rand(2,3)

tensor([[0.1117, 0.8158, 0.2626],
        [0.4839, 0.6765, 0.7539]])

In [10]:
torch.manual_seed(100)
torch.rand(2,3)

tensor([[0.1117, 0.8158, 0.2626],
        [0.4839, 0.6765, 0.7539]])

In [11]:
# using tensor
torch.tensor([[1,2,3],[4,5,6]])

tensor([[1, 2, 3],
        [4, 5, 6]])

In [12]:
# other ways

# arange
print("using arange ->", torch.arange(0,10,2))

# using linspace
print("using linspace ->", torch.linspace(0,10,10))

# using eye
print("using eye ->", torch.eye(5))

# using full
print("using full ->", torch.full((3, 3), 5))

using arange -> tensor([0, 2, 4, 6, 8])
using linspace -> tensor([ 0.0000,  1.1111,  2.2222,  3.3333,  4.4444,  5.5556,  6.6667,  7.7778,
         8.8889, 10.0000])
using eye -> tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])
using full -> tensor([[5, 5, 5],
        [5, 5, 5],
        [5, 5, 5]])


## Tensor Shapes

In [7]:
x = torch.tensor([[1,2,3],[4,5,6]])
x

tensor([[1, 2, 3],
        [4, 5, 6]])

In [9]:
x.shape

torch.Size([2, 3])

In [15]:
torch.empty_like(x)

tensor([[                  0, 7235419174270214779, 3832625088044218914],
        [7089898560249161061, 7221352008561866553, 7077183859227779430]])

In [16]:
torch.zeros_like(x)

tensor([[0, 0, 0],
        [0, 0, 0]])

In [17]:
torch.ones_like(x)

tensor([[1, 1, 1],
        [1, 1, 1]])

In [18]:
torch.rand_like(x, dtype=torch.float32)

tensor([[0.2627, 0.0428, 0.2080],
        [0.1180, 0.1217, 0.7356]])

## Tensor Data Types

In [19]:
# find data type
x.dtype

torch.int64

In [20]:
# assign data type
torch.tensor([1.0,2.0,3.0], dtype=torch.int32)

tensor([1, 2, 3], dtype=torch.int32)

In [21]:
torch.tensor([1,2,3], dtype=torch.float64)

tensor([1., 2., 3.], dtype=torch.float64)

In [22]:
# using to()
x.to(torch.float32)

tensor([[1., 2., 3.],
        [4., 5., 6.]])

| **Data Type**             | **Dtype**         | **Description**                                                                                                                                                                |
|---------------------------|-------------------|--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
| **32-bit Floating Point** | `torch.float32`   | Standard floating-point type used for most deep learning tasks. Provides a balance between precision and memory usage.                                                         |
| **64-bit Floating Point** | `torch.float64`   | Double-precision floating point. Useful for high-precision numerical tasks but uses more memory.                                                                               |
| **16-bit Floating Point** | `torch.float16`   | Half-precision floating point. Commonly used in mixed-precision training to reduce memory and computational overhead on modern GPUs.                                            |
| **BFloat16**              | `torch.bfloat16`  | Brain floating-point format with reduced precision compared to `float16`. Used in mixed-precision training, especially on TPUs.                                                |
| **8-bit Floating Point**  | `torch.float8`    | Ultra-low-precision floating point. Used for experimental applications and extreme memory-constrained environments (less common).                                               |
| **8-bit Integer**         | `torch.int8`      | 8-bit signed integer. Used for quantized models to save memory and computation in inference.                                                                                   |
| **16-bit Integer**        | `torch.int16`     | 16-bit signed integer. Useful for special numerical tasks requiring intermediate precision.                                                                                    |
| **32-bit Integer**        | `torch.int32`     | Standard signed integer type. Commonly used for indexing and general-purpose numerical tasks.                                                                                  |
| **64-bit Integer**        | `torch.int64`     | Long integer type. Often used for large indexing arrays or for tasks involving large numbers.                                                                                  |
| **8-bit Unsigned Integer**| `torch.uint8`     | 8-bit unsigned integer. Commonly used for image data (e.g., pixel values between 0 and 255).                                                                                    |
| **Boolean**               | `torch.bool`      | Boolean type, stores `True` or `False` values. Often used for masks in logical operations.                                                                                      |
| **Complex 64**            | `torch.complex64` | Complex number type with 32-bit real and 32-bit imaginary parts. Used for scientific and signal processing tasks.                                                               |
| **Complex 128**           | `torch.complex128`| Complex number type with 64-bit real and 64-bit imaginary parts. Offers higher precision but uses more memory.                                                                 |
| **Quantized Integer**     | `torch.qint8`     | Quantized signed 8-bit integer. Used in quantized models for efficient inference.                                                                                              |
| **Quantized Unsigned Integer** | `torch.quint8` | Quantized unsigned 8-bit integer. Often used for quantized tensors in image-related tasks.                                                                                     |


## Mathematical operations

### 1. Scalar operation

In [86]:
x = torch.rand(2,2)
x

tensor([[0.2243, 0.8935],
        [0.0497, 0.1780]])

In [87]:
# addition
x + 2
# substraction
x - 2
# multiplication
x * 3
# division
x / 3
# int division
(x * 100)//3
# mod
((x * 100)//3)%2
# power
x**2

tensor([[0.0503, 0.7983],
        [0.0025, 0.0317]])

### 2. Element wise operation

In [88]:
a = torch.rand(2,3)
b = torch.rand(2,3)

print(a)
print(b)

tensor([[0.3011, 0.1893, 0.9186],
        [0.2131, 0.3957, 0.6017]])
tensor([[0.4234, 0.5224, 0.4175],
        [0.0340, 0.9157, 0.3079]])


In [89]:
# add
a + b
# sub
a - b
# multiply
a * b
# division
a / b
# power
a ** b
# mod
a % b

tensor([[0.3011, 0.1893, 0.0836],
        [0.0091, 0.3957, 0.2938]])

In [90]:
c = torch.tensor([1, -2, 3, -4])

In [91]:
# abs
torch.abs(c)

tensor([1, 2, 3, 4])

In [92]:
# negative
torch.neg(c)

tensor([-1,  2, -3,  4])

In [93]:
d = torch.tensor([1.9, 2.3, 3.7, 4.4])

In [94]:
# round
torch.round(d)

tensor([2., 2., 4., 4.])

In [95]:
# ceil
torch.ceil(d)

tensor([2., 3., 4., 5.])

In [96]:
# floor
torch.floor(d)

tensor([1., 2., 3., 4.])

In [97]:
# clamp
torch.clamp(d, min=2, max=3)

tensor([2.0000, 2.3000, 3.0000, 3.0000])

### 3. Reduction operation

In [98]:
e = torch.randint(size=(2,3), low=0, high=10, dtype=torch.float32)
e

tensor([[2., 3., 1.],
        [0., 2., 1.]])

In [99]:
# sum
torch.sum(e)
# sum along columns
torch.sum(e, dim=0)
# sum along rows
torch.sum(e, dim=1)

tensor([6., 3.])

In [100]:
# mean
torch.mean(e)
# mean along col
torch.mean(e, dim=0)

tensor([1.0000, 2.5000, 1.0000])

In [101]:
# median
torch.median(e)

tensor(1.)

In [102]:
# max and min
torch.max(e)
torch.min(e)

tensor(0.)

In [103]:
# product
torch.prod(e)

tensor(0.)

In [104]:
# standard deviation
torch.std(e)

tensor(1.0488)

In [105]:
# variance
torch.var(e)

tensor(1.1000)

In [106]:
# argmax
torch.argmax(e)

tensor(1)

In [107]:
# argmin
torch.argmin(e)

tensor(3)

### 4. Matrix operations

In [108]:
f = torch.randint(size=(2,3), low=0, high=10)
g = torch.randint(size=(3,2), low=0, high=10)

print(f)
print(g)

tensor([[2, 7, 9],
        [2, 4, 6]])
tensor([[6, 8],
        [4, 9],
        [0, 7]])


In [109]:
# matrix multiplcation
torch.matmul(f, g)

tensor([[ 40, 142],
        [ 28,  94]])

In [110]:
vector1 = torch.tensor([1, 2])
vector2 = torch.tensor([3, 4])

# dot product
torch.dot(vector1, vector2)

tensor(11)

In [111]:
# transpose
torch.transpose(f, 0, 1)

tensor([[2, 2],
        [7, 4],
        [9, 6]])

In [112]:
h = torch.randint(size=(3,3), low=0, high=10, dtype=torch.float32)
h

tensor([[9., 2., 7.],
        [0., 2., 4.],
        [4., 6., 2.]])

In [113]:
# determinant
torch.det(h)

tensor(-204.0000)

In [114]:
# inverse
torch.inverse(h)

tensor([[ 0.0980, -0.1863,  0.0294],
        [-0.0784,  0.0490,  0.1765],
        [ 0.0392,  0.2255, -0.0882]])

### 5. Comparison operations

In [115]:
i = torch.randint(size=(2,3), low=0, high=10)
j = torch.randint(size=(2,3), low=0, high=10)

print(i)
print(j)

tensor([[1, 0, 5],
        [1, 0, 0]])
tensor([[2, 2, 3],
        [7, 1, 5]])


In [116]:
# greater than
i > j
# less than
i < j
# equal to
i == j
# not equal to
i != j
# greater than equal to

# less than equal to

tensor([[True, True, True],
        [True, True, True]])

### 6. Special functions

In [117]:
k = torch.randint(size=(2,3), low=0, high=10, dtype=torch.float32)
k

tensor([[0., 2., 3.],
        [7., 0., 2.]])

In [118]:
# log
torch.log(k)

tensor([[  -inf, 0.6931, 1.0986],
        [1.9459,   -inf, 0.6931]])

In [119]:
# exp
torch.exp(k)

tensor([[1.0000e+00, 7.3891e+00, 2.0086e+01],
        [1.0966e+03, 1.0000e+00, 7.3891e+00]])

In [120]:
# sqrt
torch.sqrt(k)

tensor([[0.0000, 1.4142, 1.7321],
        [2.6458, 0.0000, 1.4142]])

In [121]:
# sigmoid
torch.sigmoid(k)

tensor([[0.5000, 0.8808, 0.9526],
        [0.9991, 0.5000, 0.8808]])

In [122]:
# softmax
torch.softmax(k, dim=0)

tensor([[9.1105e-04, 8.8080e-01, 7.3106e-01],
        [9.9909e-01, 1.1920e-01, 2.6894e-01]])

In [123]:
# relu
torch.relu(k)

tensor([[0., 2., 3.],
        [7., 0., 2.]])

## Inplace Operations

In [61]:
m = torch.rand(2,3)
n = torch.rand(2,3)

print(m)
print(n)

tensor([[0.6574, 0.3451, 0.0453],
        [0.9798, 0.5548, 0.6868]])
tensor([[0.4920, 0.0748, 0.9605],
        [0.3271, 0.0103, 0.9516]])


In [62]:
m.add_(n)

tensor([[1.1494, 0.4199, 1.0058],
        [1.3069, 0.5650, 1.6384]])

In [63]:
m

tensor([[1.1494, 0.4199, 1.0058],
        [1.3069, 0.5650, 1.6384]])

In [64]:
n

tensor([[0.4920, 0.0748, 0.9605],
        [0.3271, 0.0103, 0.9516]])

In [65]:
torch.relu(m)

tensor([[1.1494, 0.4199, 1.0058],
        [1.3069, 0.5650, 1.6384]])

In [66]:
m.relu_()

tensor([[1.1494, 0.4199, 1.0058],
        [1.3069, 0.5650, 1.6384]])

In [67]:
m

tensor([[1.1494, 0.4199, 1.0058],
        [1.3069, 0.5650, 1.6384]])

## Copying a Tensor

In [68]:
a = torch.rand(2,3)
a

tensor([[0.2855, 0.2324, 0.9141],
        [0.7668, 0.1659, 0.4393]])

In [69]:
b = a

In [70]:
b

tensor([[0.2855, 0.2324, 0.9141],
        [0.7668, 0.1659, 0.4393]])

In [71]:
a[0][0] = 0

In [72]:
a

tensor([[0.0000, 0.2324, 0.9141],
        [0.7668, 0.1659, 0.4393]])

In [73]:
b

tensor([[0.0000, 0.2324, 0.9141],
        [0.7668, 0.1659, 0.4393]])

In [74]:
id(a)

135154526493712

In [75]:
id(b)

135154526493712

In [76]:
b = a.clone()

In [77]:
a

tensor([[0.0000, 0.2324, 0.9141],
        [0.7668, 0.1659, 0.4393]])

In [78]:
b

tensor([[0.0000, 0.2324, 0.9141],
        [0.7668, 0.1659, 0.4393]])

In [79]:
a[0][0] = 10

In [80]:
a

tensor([[10.0000,  0.2324,  0.9141],
        [ 0.7668,  0.1659,  0.4393]])

In [81]:
b

tensor([[0.0000, 0.2324, 0.9141],
        [0.7668, 0.1659, 0.4393]])

In [82]:
id(a)

135154526493712

In [83]:
id(b)

135154526497168

# Tensor Operations on GPU

In [3]:
torch.cuda.is_available()

False

In [4]:
device=torch.device("cuda")

In [5]:
# Creating new tensor on GPU

torch.rand((2,3),device=device)

RuntimeError: Found no NVIDIA driver on your system. Please check that you have an NVIDIA GPU and installed a driver from http://www.nvidia.com/Download/index.aspx

In [ ]:
# To make the process speedy and smoothly. Either create tensors on GPU or move an existing tensor to GPU

In [127]:
a = torch.rand((2,3))
a

tensor([[0.6555, 0.7667, 0.2269],
        [0.7555, 0.6458, 0.3673]])

In [128]:
# Above result was run into CPU, since it has not written device info. into tensor result

# Now, let's move to GPU

b = a.to(device)
b                          # see the result has device info, ran into GPU

tensor([[0.6555, 0.7667, 0.2269],
        [0.7555, 0.6458, 0.3673]], device='cuda:0')

In [129]:
b + 5

tensor([[5.6555, 5.7667, 5.2269],
        [5.7555, 5.6458, 5.3673]], device='cuda:0')

# Reshaping Tensors

In [4]:
a = torch.ones((2,3))
a

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [5]:
a.reshape((3,2))

tensor([[1., 1.],
        [1., 1.],
        [1., 1.]])

In [6]:
# flatten
a.flatten()

tensor([1., 1., 1., 1., 1., 1.])

In [136]:
b = torch.rand((2,3,4))
b

tensor([[[0.1770, 0.2966, 0.9925, 0.2103],
         [0.1292, 0.1719, 0.9127, 0.6818],
         [0.1953, 0.9991, 0.1133, 0.0135]],

        [[0.1450, 0.7819, 0.3134, 0.2983],
         [0.3436, 0.2028, 0.9792, 0.4947],
         [0.3617, 0.9687, 0.0359, 0.3041]]])

In [138]:
# permute
# I want to make shape(2,3,4)-->(0,1,2) indices
# So now 4 to be at 0 index (2,)
# 2 to be at 1 index (2,0,)
# 3 to be at 2 index (2,0,1)
b.permute(2,0,1).shape

torch.Size([4, 2, 3])

In [144]:
# unsqueeze
c = torch.rand((266,266,3))
c.unsqueeze(2).shape       # you are adding dimension. Usually it is used in images data

torch.Size([266, 266, 1, 3])

In [145]:
# squeeze (Opposite to above)

d = torch.rand((1,23))
d.squeeze(0).shape          # 1 will remove and it will be only 1 dimensions

torch.Size([23])

# Numpy and Pytorch

In [146]:
import numpy as np


In [150]:
a = torch.tensor([1,2,3])
a

tensor([1, 2, 3])

In [152]:
b = a.numpy()
b
type(b)

numpy.ndarray

In [153]:
c = np.array([1,2,3])
c

array([1, 2, 3])

In [154]:
# Create tensor from numpy array
torch.from_numpy(c)

tensor([1, 2, 3])